### ISSUE TITLE
Special characters garbled in windows (CMD, Powershell)

### ISSUE THREAD

**Issue by avitex** [rrrene/credo#422]
### Environment

* Credo version: `0.8.5`
* Erlang/Elixir version: `1.5.0`
* Operating system: `Windows 10 (build 15063)`

Special characters ([arrows](https://github.com/rrrene/credo/blob/74dbf37983ae27c6f2443911e40a07ec1069e85f/lib/credo/cli/output.ex#L68), [edge](https://github.com/rrrene/credo/blob/74dbf37983ae27c6f2443911e40a07ec1069e85f/lib/credo/cli/output/ui.ex#L2)) display as garbled text in command prompt and Powershell.
Works as expected in git bash (as expected).

## Expected output (git bash)
![image](https://user-images.githubusercontent.com/5110816/29099172-00fbbf24-7ce7-11e7-8329-6c4bbe9b7c52.png)

## Actual output (Powershell)
![image](https://user-images.githubusercontent.com/5110816/29099224-55e7de1e-7ce7-11e7-883b-05d3ba097898.png)

**Comment by NobbZ** [comment]
You have to enable unicode support in PowerShell. I've tried to pre-google, but found only conversations like "do this", "doesn't work for me", "but for me it does".

It seems as if you have to find the solution that works for you on your own.

**Comment by avitex** [comment]
An alternative solution would be a feature to change the characters, and provide a overridable working default for `{:win32, _} == os:type()`.
I'm quite happy to craft a PR up for this when I get some time.
Not a serious issue by any means.

**Comment by luckynum7** [comment]
Did some research,

Found the same issue in https://github.com/dart-lang/sdk/issues/28948#issuecomment-283574798 (dart)

I've tried to use the same method for credo, but found that it uses https://github.com/rrrene/bunt for coloring output. Maybe I'll check that one later (help wanted)

And a blog use a powershell function to resolve the output:
[un-messing Unicode in PowerShell](https://blogs.msdn.microsoft.com/sergey_babkins_blog/2016/12/29/un-messing-unicode-in-powershell/)
```
PowerShell has a bit of a problem with accepting the output of the native commands that print Unicode into its pipelines. PowerShell tries to be smart in determining whether the command prints Unicode or ASCII, so if the output happens to be nicely formatted and contains the proper Unicode byte order mark (0xFF 0xFE) than it gets accepted OK.
```

Here's the wiki link on byte order mark (BOM): https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by avitex** [comment]
`chcp 65001` works in Powershell and CMD, another factor that contributes is the font you use. Otherwise you just get unhandled character boxes as replacement. I've been using `Source Code Pro` and it works fine.

**Comment by rrrene** [comment]
Sorry for not checking in for a while.

So does that mean that we just have to insert a BOM at the start of the output for PowerShell to be fine? What about CMD in that case?

**Comment by luckynum7** [comment]
@rranelli I've tried with https://github.com/rrrene/credo and https://github.com/rrrene/bunt after the above comment. But didn't get the correct result.
I'm use the `[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8` way now.

If you can tell me the right place to add the BOM, I'd be glad to test it.

**Comment by CollinChaffin** [comment]
Convert your profile and any file you're dealing with to UTF8 **WITH BOM**

**Comment by TheFirstAvenger** [comment]
If I am reading this correctly, I think this issue should actually be in bunt, as this issue affects anything that uses bunt. I believe the BOM would need to be inserted there, and it would fix anything that uses it including credo?

**Comment by TheFirstAvenger** [comment]
@rrrene What are your thoughts on moving this issue to the bunt repo? Do you agree that this is an issue that should be addressed in the underlying library?

**Comment by rrrene** [comment]
@TheFirstAvenger I was able to install Erlang/Elixir/Credo on a Windows 10 box and got this in Powershell:

![Powershell_without_BOM](https://user-images.githubusercontent.com/311914/77574393-36cfd880-6ed2-11ea-9231-a2271e8fbf7d.PNG)

When I added a BOM in front of the output, it just padded the output in an unexpected way, but did not fix the issue:

![Powershell_with_BOM](https://user-images.githubusercontent.com/311914/77574486-5ff06900-6ed2-11ea-8224-4a573c88166d.PNG)

In Windows Terminal, the unicode arrows indicating the priority are printed correctly with Credo `1.3.1`:

![Powershell_without_BOM_in_WindowsTerminal](https://user-images.githubusercontent.com/311914/77574772-d2614900-6ed2-11ea-8ff1-4ab8b1b4d20d.PNG)

Based on this, by no means exhaustive, analysis, I am not sure what we can do from Credo's side here. WDYT?

**Comment by dkgitdev** [comment]
Here's what I got from powershell on my Russian-based Windows 2004 (19041.29)

![изображение](https://user-images.githubusercontent.com/36101416/87201668-b9589880-c307-11ea-9f22-d1d69bed4257.png)

I suggest using this arrow as a middle one -- ⇒ -- it's 8658 in ASCII, and | as a vertical line (ASCII 124)

Apparently, I'm running utf8, so it's definitely strange
![изображение](https://user-images.githubusercontent.com/36101416/87202378-199c0a00-c309-11ea-802e-02cc2a9921f3.png)

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.

**Comment by dkgitdev** [comment]
Well, if one cannot reproduce the bug, doesn't it mean it's fixed? :)
